server:
  port: 8080

spring:
  datasource:
    url: jdbc:log4jdbc:mariadb://192.168.45.4:3306/test
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: tester
    password: tester
    maximumPoolSize: 3
    sql:
      init:
        mode: never
    jpa:
      database-platform: org.hibernate.dialect.MariaDB10Dialect
      hibernate:
        ddl_auto: update
        dialect: org.hibernate.dialect.MariaDB10Dialect
        format_sql: true
        show_sql: true
      main:
        allow-bean-definition-overriding: true
      servlet:
        multipart:
          maxFileSize: 50MB
          maxRequestSize: 50MB
      open-in-view: false